services:
  database:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest

  rabbitmq:
    image: rabbitmq:management

  gautracker.api:
    image: ${DOCKER_REGISTRY-}gautrackerapi
    build:
      context: .
      dockerfile: Src/Services/GauTracker/GauTracker.API/Dockerfile

  background.api:
    image: ${DOCKER_REGISTRY-}backgroundapi
    build:
      context: .
      dockerfile: Src/Services/Background/Background.API/Dockerfile

volumes:
  postgres_gautracker:
  openobserve_data:  