namespace WebApi.Application.Features.TravelHistoryFileFeatures.GetTravelHistoryFileDownloadUrl;

public sealed record GetTravelHistoryFileDownloadUrlResponse(string FileName, Uri DownloadUrl, DateTimeOffset ExpiresAt);
