// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shared.Persistence.Data.Contexts;

#nullable disable

namespace Shared.Persistence.Data.Migrations.GauMigrations
{
    [DbContext(typeof(GauContext))]
    [Migration("20260621085143_AddStationAndService")]
    partial class AddStationAndService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Domain.Entities.Card", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Card", "public");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Description");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Description"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Description"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("Service", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Rapid rail access via the personalised Gold Card (tap in / tap out).",
                            Name = "Train service"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Secure, access-controlled parking; fee auto-charged to Gold Card on exit.",
                            Name = "Parking"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Integrated Gautrain buses connecting the station to surrounding areas.",
                            Name = "Feeder & distribution buses"
                        });
                });

            modelBuilder.Entity("Shared.Domain.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsTerminal")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Address");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Address"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Address"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("Station", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Acacia & Grosvenor Street, east of Pretoria CBD",
                            IsTerminal = true,
                            Latitude = -25.747650m,
                            Longitude = 28.238000m,
                            Name = "Hatfield",
                            StationType = "AtGrade"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Scheiding St, adjacent to Pretoria Main Station",
                            IsTerminal = false,
                            Latitude = -25.758167m,
                            Longitude = 28.189467m,
                            Name = "Pretoria",
                            StationType = "AtGrade"
                        },
                        new
                        {
                            Id = 3,
                            Address = "West Avenue & Gerard Street, near Centurion Lake",
                            IsTerminal = false,
                            Latitude = -25.851617m,
                            Longitude = 28.189733m,
                            Name = "Centurion",
                            StationType = "Elevated"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Old Pretoria-Johannesburg Road (K101)",
                            IsTerminal = false,
                            Latitude = -25.996483m,
                            Longitude = 28.137583m,
                            Name = "Midrand",
                            StationType = "AtGrade"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Cnr Football & Laduma, Alexandra",
                            IsTerminal = false,
                            Latitude = -26.083917m,
                            Longitude = 28.111633m,
                            Name = "Marlboro",
                            StationType = "AtGrade"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Rivonia Road, between West St & Fifth Ave",
                            IsTerminal = false,
                            Latitude = -26.107800m,
                            Longitude = 28.057500m,
                            Name = "Sandton",
                            StationType = "Underground"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Oxford Road, between Baker St & Tyrwhitt Ave",
                            IsTerminal = false,
                            Latitude = -26.145250m,
                            Longitude = 28.043867m,
                            Name = "Rosebank",
                            StationType = "Underground"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Cnr Smit & Wolmarans St, Braamfontein",
                            IsTerminal = true,
                            Latitude = -26.195533m,
                            Longitude = 28.041550m,
                            Name = "Park",
                            StationType = "Underground"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Anson Street, Kempton Park",
                            IsTerminal = false,
                            Latitude = -26.128333m,
                            Longitude = 28.225233m,
                            Name = "Rhodesfield",
                            StationType = "AtGrade"
                        },
                        new
                        {
                            Id = 10,
                            Address = "OR Tambo International Airport, Kempton Park",
                            IsTerminal = true,
                            Latitude = -26.132933m,
                            Longitude = 28.231567m,
                            Name = "OR Tambo",
                            StationType = "Elevated"
                        });
                });

            modelBuilder.Entity("Shared.Domain.Entities.StationService", b =>
                {
                    b.Property<int>("StationId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("StationId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("StationService", "public");

                    b.HasData(
                        new
                        {
                            StationId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            StationId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            StationId = 1,
                            ServiceId = 3
                        },
                        new
                        {
                            StationId = 2,
                            ServiceId = 1
                        },
                        new
                        {
                            StationId = 2,
                            ServiceId = 2
                        },
                        new
                        {
                            StationId = 2,
                            ServiceId = 3
                        },
                        new
                        {
                            StationId = 3,
                            ServiceId = 1
                        },
                        new
                        {
                            StationId = 3,
                            ServiceId = 2
                        },
                        new
                        {
                            StationId = 3,
                            ServiceId = 3
                        },
                        new
                        {
                            StationId = 4,
                            ServiceId = 1
                        },
                        new
                        {
                            StationId = 4,
                            ServiceId = 2
                        },
                        new
                        {
                            StationId = 4,
                            ServiceId = 3
                        },
                        new
                        {
                            StationId = 5,
                            ServiceId = 1
                        },
                        new
                        {
                            StationId = 5,
                            ServiceId = 2
                        },
                        new
                        {
                            StationId = 5,
                            ServiceId = 3
                        },
                        new
                        {
                            StationId = 6,
                            ServiceId = 1
                        },
                        new
                        {
                            StationId = 6,
                            ServiceId = 2
                        },
                        new
                        {
                            StationId = 6,
                            ServiceId = 3
                        },
                        new
                        {
                            StationId = 7,
                            ServiceId = 1
                        },
                        new
                        {
                            StationId = 7,
                            ServiceId = 2
                        },
                        new
                        {
                            StationId = 7,
                            ServiceId = 3
                        },
                        new
                        {
                            StationId = 8,
                            ServiceId = 1
                        },
                        new
                        {
                            StationId = 8,
                            ServiceId = 2
                        },
                        new
                        {
                            StationId = 8,
                            ServiceId = 3
                        },
                        new
                        {
                            StationId = 9,
                            ServiceId = 1
                        },
                        new
                        {
                            StationId = 9,
                            ServiceId = 2
                        },
                        new
                        {
                            StationId = 9,
                            ServiceId = 3
                        },
                        new
                        {
                            StationId = 10,
                            ServiceId = 1
                        });
                });

            modelBuilder.Entity("Shared.Domain.Entities.TravelHistoryFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BlobContainer")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("CardId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DateUploaded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("BlobKey")
                        .IsUnique();

                    b.HasIndex("CardId");

                    b.HasIndex("DisplayName");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DisplayName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("DisplayName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("FileName");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FileName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("FileName"), new[] { "gin_trgm_ops" });

                    b.ToTable("TravelHistoryFile", "public");
                });

            modelBuilder.Entity("Shared.Domain.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.ToTable("User", "public");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Card", b =>
                {
                    b.HasOne("Shared.Domain.Entities.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Domain.Entities.StationService", b =>
                {
                    b.HasOne("Shared.Domain.Entities.Service", "Service")
                        .WithMany("StationServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Domain.Entities.Station", "Station")
                        .WithMany("StationServices")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Shared.Domain.Entities.TravelHistoryFile", b =>
                {
                    b.HasOne("Shared.Domain.Entities.Card", "Card")
                        .WithMany("TravelHistoryFiles")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Card", b =>
                {
                    b.Navigation("TravelHistoryFiles");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Service", b =>
                {
                    b.Navigation("StationServices");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Station", b =>
                {
                    b.Navigation("StationServices");
                });

            modelBuilder.Entity("Shared.Domain.Entities.User", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
